jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm run test
  deploy: 
    name: deploy
    command: curl -X POST -d {} ${hook} 
workflows: 
  version: 2
    build_test_and_deploy: 
      jobs: 
        - build
        - test:
          requires: 
            - build
        - deploy:
          requires: 
            - test

